main/diary/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r"^enter_question/$",views.question_enter,name='question_enter'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'), 
    url(r'^$',views.event,name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
  
]

main/diary/models.py
from django.db import models
from django.urls import reverse
from django import template

import datetime as dt
import random

# model
class Question(models.Model):
  Question = models.CharField(max_length=50)

  def __str__(self):
    return self.Question
class Event(models.Model):
    WTV = 'wtv'
    STFU = 'stfu'
    WTF = 'wtf'
    choices = [WTV,STFU,WTF]
    random_questions = [
        (WTV,'How are you today?'),
        (STFU,'what\'s up?'),
        (WTF,'How do you do?')
    ]

    title = models.CharField(max_length=50, choices=random_questions,default=random.choice(choices))
    description = models.TextField()
    start_time = models.DateTimeField(auto_now=dt.datetime.now())
    end_time = models.DateTimeField(auto_now=dt.datetime.now() + dt.timedelta(days=1))

    @property
    def get_html_url(self):
        url = reverse('diary:event_edit',args=(self.id,))
        return f'<a href="{url}">{self.title}</a>'
    
    def __str__(self):
        return self.title



    

main/diary/forms.py
from django import forms
from .models import *

class Enter_Question(forms.ModelForm):
    
    class Meta:
        model = Question
        fields = ['Question']
    
    def save(self,commit=True):
        user = super(Enter_Question,self).save(commit=False)
        user.Question = self.cleaned_data['Question']
        if commit:
            user.save()
        return user

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        # widgets = {
        #     'start_time': forms.DateInput(attrs={'type':'datetime-local'},format='%Y-%m-%d'),
        #     'end_time': forms.DateInput(attrs={'type': 'datetime-local'},format='%Y-%m-%d'),
        # }
        fields = '__all__'
    
    def __init__(self,*args,**kwargs):
        super(EventForm,self).__init__(*args,**kwargs)
        # self.fields['start_time'].input_formats = ('%Y-%m-%d',)
        # self.fields['end_time'].input_formats = ('%Y-%m-%d',)
        
    

main/diary/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe

from .forms import EventForm, Enter_Question
from .models import *
from .utils import Calendar
from calendar import monthrange
from datetime import datetime,timedelta,date


# Create your views here.

def index(request):
    return HttpResponse('work already')

def question_enter(request):
  
    if request.POST:
        form = Enter_Question(request.POST)
        if form.is_valid():
            Question = form.cleaned_data['Question']
            form.save()
            return redirect('/')
    else:
        form = Enter_Question()
        return render(request,'questions.html',{'form':form})

class CalendarView(generic.ListView):
    model = Event
    template_name = 'diary/calendar.html'
    print(Event.title)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('day',None))
        cal = Calendar(d.year,d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year,month = (int(x) for x in req_day.split('-'))
        return date(year,month,day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month='+str(prev_month.year)+'-'+str(prev_month.month)
    return month

def next_month(d):
    days_in_month = monthrange(d.year,d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month='+str(next_month.year)+'-'+str(next_month.month)
    return month

def event(request,event_id=None):
    question = Question.objects.order_by('?')[0]
    # random_items = random.choice(question)
    

    instance = Event()
    if event_id:
        instance = get_object_or_404(Event,pk=event_id)
    else:
        instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)

    if request.POST and form.is_valid():
        form.save()
        question.save()
        return HttpResponseRedirect(reverse('diary:calendar'))
    return render(request,'diary/event.html',{'form':form,"question":str(question)})

main/diary/templates/diary/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

main/diary/templates/diary/calendar.html
{% extends 'diary/base.html' %}

{% block content %}
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'diary:calendar' %}?{{ prev_month}}">Previous Month</a>
    <a class="btn btn-info right" href="{% url 'diary:calendar' %}?{{next_month}}">Next Month</a>
    <a class="btn btn-info center" href="{% url 'diary:event_new' %}">New Record</a>
</div>
{{ calendar }}
{% endblock %}

main/diary/templates/diary/event.html
{% extends 'diary/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'diary:calendar' %}"> Calendar </a>
  <a class="btn btn-info right" href="{% url 'diary:question_enter' %}"> Enter Question </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
   <p>{{ question }}</p>
    
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

main/diary/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <style>
    .nav-link{
      color:white;
    }
  </style>
  </head>
  <body>
     <!-- A grey horizontal navbar that becomes vertical on small screens -->
    <nav class="navbar navbar-expand-sm justify-content-end" style="background-color: #1383c6 !important; color:white;">

      <!-- Links -->
      <ul class="navbar-nav ">
        <li class="nav-item">
         
        </li>
        
      </ul>

    </nav> 
    <div class="container">
      {% block content %}


      {% endblock %}
  
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/diary/templates/questions.html
{% extends 'layout.html'%}

{% block title %}
Your Diary
{% endblock %}


{% block content %}
    <div class="container">
        <div class='col-12'>
            <h1 class='mt-2'>Enter a Question</h1>
            
            <hr class='mt-0 mb-4'>
            {% load static %}
            {% load crispy_forms_tags %}
            <form method="post"  >
                {% csrf_token %}
                {{form|crispy}}
                <input type='submit' class='btn btn-primary' value='Click' name='mybtn' />
            </form>
        </div>
    </div>
{% endblock %}